### ISSUE TITLE
Bounding box query with two points

### ISSUE THREAD

**Issue by Selvinaz1984** [NLPchina/elasticsearch-sql#171]
Hello,

I have a question to define a sql query with bounding box filter of Elasticsearch with two points (latitude and longitude).
The gps point information is stored in nested type attributes:
"attributes" : [ {
    "paramKey" : "BLOCK",
    "value" : "880"
  },
    "paramKey" : "GEODIRECTION",
    "value" : "66"
  }, {
    "paramKey" : "GPSX",
    "value" : "60071316"
  }, {
    "paramKey" : "GPSY",
    "value" : "507736639"
  }

How can I declare a query now, I have seen that just one field can be put in the query syntax??

**Comment by eliranmoyal** [comment]
not sure if this is possible in elasticsearch.. the geoBoundingBox filter is used only for GeoPoints types..
read about it here
https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-dsl-geo-bounding-box-query.html

you need to change your document and mapping in order to use it.

also it looks like you dont even save it as numbers.. so a workaround like asking
 ```sql
select * from index where nested('attributes',attributes.paramKey = 'GPSX' and attributes.value < topLeftX ) etc..
```  
won't work either
