### ISSUE TITLE
1.4.1版本,使用报错

### ISSUE THREAD

**Issue by bigbo** [NLPchina/elasticsearch-sql#25]
Error: {"error":"RemoteTransportException[[Novs][inet[localhost:9300]][indices/create]]; nested: InvalidIndexNameException[[_sql] Invalid index name [_sql], must not start with '_']; ","status":400}

另外一个es节点上报:
{"error":"NoClassDefFoundError[org/durid/sql/ast/statement/SQLSelectQuery]; nested: ClassNotFoundException[org.durid.sql.ast.statement.SQLSelectQuery]; ","status":500}

es版本为:1.3.6

页面上我填写的是本机的9200啊,不知道为什么网络请求是9300.语句就是readme上的示例.

**Comment by dpj2010** [comment]
Elasticsearch 2.3.1

./bin/plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/2.3.1.0/elasticsearch-sql-2.3.1.0.zip 
After doing this, you need to restart the Elasticsearch server. Otherwise you may get errors like Invalid index name [sql], must not start with '']; ","status":400}.

需要重启
