### ISSUE TITLE
Invalid index name [_sql]

### ISSUE THREAD

**Issue by kaliseo** [NLPchina/elasticsearch-sql#29]
Unable to make a query.

My ElasticSearch version is 1.4.1

**Comment by omershelef** [comment]
What is the query you were trying to make?

**Comment by kaliseo** [comment]
Simple match_all query

Le Wed Jan 07 2015 at 19:03:52, Omer Shelef <notifications@github.com> a
écrit :

**Comment by kaliseo** [comment]
"SELECT * FROM [myindex] LIMIT 100;"

Le Thu Jan 08 2015 at 21:55:38, Thierry LEFORESTIER <kali.seo@gmail.com> a
écrit :

**Comment by omershelef** [comment]
Elasticsearch-sql use MySQL dialect. square brackets is invalid in MySQL. if your index name is "myindex" just drop the brackets:
```
SELECT * FROM myindex
```

if your index name is "[myindex]".  use backticks:
```
SELECT * FROM `[myindex]`
```

**Comment by vixriihi** [comment]
Quoting doesn't seem to help (ES version 1.4.2)
My query is:
```
SELECT * FROM `test_1`
```
and the result is always the same (with and without quotes):
```
{"error":"InvalidIndexNameException[[_sql] Invalid index name [_sql], must not start with '_']","status":400}
```

**Comment by omershelef** [comment]
What version of elasticsearch-sql are you using?

**Comment by vixriihi** [comment]
1.2

**Comment by kaliseo** [comment]
I didn't set bracket, it was just to give the index example ^^. Sorry

**Comment by omershelef** [comment]
I am trying to reproduce your problem. I installed elasticsearch 1.4.2 and elasticsearch-sql 1.2.
but it seems to working fine on my computer.
according to the error it seems that elasticsearch trying to query on index named "_sql" instead of the "test_1"...

Are you trying to query using the web frontend or the rest api? if you are using rest, what is the exact url you used?

what operating system are you using?
what java version?

**Comment by vixriihi** [comment]
Yes. I was using web frontend and the jar was missing. Re-installed and now everything is working as expected. Thank you for a great plugin

**Comment by omershelef** [comment]
Happy to help. Do you have any idea why this jar was missing? you installed the plugin in a different way?

**Comment by vixriihi** [comment]
Unfortunetly I don't. I used the one liner from the [frontpage](https://github.com/NLPchina/elasticsearch-sql#elasticsearch-14x) to intall.

**Comment by VictorCano** [comment]
Hi, i'm also experiencing this error, although in my sql plugin folder the .jar file exists.
```/usr/share/elasticsearch/plugins/sql# ls
_site  elasticsearch-sql-1.3.jar```

I'm using ElasticSearch 1.4.2 and the 1.3 version of the plugin. Do you have any idea how I could get to fix this? Thanks!!

**Comment by TarasB** [comment]
Hi, 

The same problem. File elasticsearch-sql-1.3.1.jar exists.

Error message:
 Error: {"error":"InvalidIndexNameException[[_sql] Invalid index name [_sql], must not start with '_']","status":400}

I tried ElasticSearch 1.4.4 and 1.5.0 - result is the same.

Additional info:
OS - Centos 6.5
Java - Java(TM) SE Runtime Environment (build 1.7.0_60-b19)

Thank you,
Taras

**Comment by dpj2010** [comment]
Elasticsearch 2.3.1

./bin/plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/2.3.1.0/elasticsearch-sql-2.3.1.0.zip 
After doing this, you need to restart the Elasticsearch server. Otherwise you may get errors like Invalid index name [sql], must not start with '']; ","status":400}.
