### ISSUE TITLE
Plan for Elasticsearch 5.0?

### ISSUE THREAD

**Issue by dangxunb** [NLPchina/elasticsearch-sql#316]
Hi, is there any plan for Elasticsearch 5.0.x?

**Comment by eliranmoyal** [comment]
Yes , I will work on this soon

**Comment by oreak** [comment]
@eliranmoyal  great  work

**Comment by eliranmoyal** [comment]
I am pretty much done with rest plugin and jdbc
but since site plugins are not supported anymore I am not sure what to do with the site
Should I make a standalone version of the site with something like node.exe ?

**Comment by eliranmoyal** [comment]
This is the plugin for elasticsearch 5.0 tested against elasticsearch 5.0.1
you can use the rest api  and the jdbc client.
Since elasticsearch disabled plugin sites on elasticsearch5 you can't use it like you used to.
If you want to use the site you can  just open the index.html in elastic_home/plugins/sql/_site
(make sure to add to elasticsearch.yml cors flags in order for the site to work.)
I'm trying to work on kibana plugin for the site, but if i won't succeed i'll just add a node server to host it.
Tell me if you are having any problems , an official release will come later this week
[elasticsearch-sql.zip](https://github.com/NLPchina/elasticsearch-sql/files/628894/elasticsearch-sql.zip)

**Comment by dangxunb** [comment]
Great! Thank you for all of this work! You received my #1 honor!

**Comment by eliranmoyal** [comment]
https://github.com/NLPchina/elasticsearch-sql/releases/tag/5.0.1

**Comment by dangxunb** [comment]
Can you push the newest artifact to maven central? I can just found the 2.x version:
https://mvnrepository.com/artifact/org.nlpcn/elasticsearch-sql

**Comment by ansjsun** [comment]
ok i will did it ..

**Comment by ansjsun** [comment]
i have commit maven center , later you will see it in mvnrespository

**Comment by dangxunb** [comment]
Hey I still can't see it in maven central, is it normal?

**Comment by ansjsun** [comment]
@dangxunb  http://mvnrepository.com/artifact/org.nlpcn/elasticsearch-sql
