### ISSUE TITLE
Invalid index name [_sql] 

### ISSUE THREAD

**Issue by TarasB** [NLPchina/elasticsearch-sql#51]
Hi All,

Could you please reopen issue #29 (Invalid index name [_sql] ) ?
There are two new comments to  issue #29 but since this issue is closed I am not sure if you follow new comments.

Thank you,
Taras

**Comment by TarasB** [comment]
I just found that issue #42 describes the same problem. I am closing this issue.

Thank you,
Taras

**Comment by dpj2010** [comment]
Elasticsearch 2.3.1

./bin/plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/2.3.1.0/elasticsearch-sql-2.3.1.0.zip 
After doing this, you need to restart the Elasticsearch server. Otherwise you may get errors like Invalid index name [sql], must not start with '']; ","status":400}.
