### ISSUE TITLE
Example Site Not working

### ISSUE THREAD

**Issue by mrshidashrf** [NLPchina/elasticsearch-sql#629]
Hi, i want to integrate your plugin into elasitcsearch but needs to test it before but unfortunately your provided link http://essql.nlpcn.org/  not working

**Comment by leonlu001** [comment]
The site just for explain SQL to DSL, you need install this plugin to elastic search, than test it.发自我的华为手机-------- 原始邮件 --------主题：[NLPchina/elasticsearch-sql] Example Site Not working (#629)发件人：mrshidashrf 收件人：NLPchina/elasticsearch-sql 抄送：Subscribed Hi, i want to integrate your plugin into elasitcsearch but needs to test it before but unfortunately your provided link http://essql.nlpcn.org/  not working

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/NLPchina/elasticsearch-sql","title":"NLPchina/elasticsearch-sql","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/NLPchina/elasticsearch-sql"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Example Site Not working (#629)"}],"action":{"name":"View Issue","url":"https://github.com/NLPchina/elasticsearch-sql/issues/629"}}}

**Comment by shi-yuan** [comment]
It's OK now!

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-sql/issues/698
