### ISSUE TITLE
高亮可以实现么？

### ISSUE THREAD

**Issue by JacksonMu** [NLPchina/elasticsearch-sql#645]
搜索结果高亮怎么展现？

**Comment by leonlu001** [comment]
返回的json 对象里面有个highlights的节点，就是你需要高亮的内容发自我的华为手机-------- 原始邮件 --------主题：[NLPchina/elasticsearch-sql] 高亮可以实现么？ (#645)发件人：穆鹏 收件人：NLPchina/elasticsearch-sql 抄送：Subscribed 搜索结果高亮怎么展现？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/NLPchina/elasticsearch-sql","title":"NLPchina/elasticsearch-sql","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/NLPchina/elasticsearch-sql"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"高亮可以实现么？ (#645)"}],"action":{"name":"View Issue","url":"https://github.com/NLPchina/elasticsearch-sql/issues/645"}}}

**Comment by JacksonMu** [comment]
@leonlu001 那请问对应的sql怎么写？例如select * from tableA where name like "%leonlu%", 我希望的是name字段如果包含leonlu的话，就被搜索出来了，并且将leonlu高亮。

**Comment by shi-yuan** [comment]
[Highlight](https://github.com/NLPchina/elasticsearch-sql/wiki/Highlight)

**Comment by JacksonMu** [comment]
@shi-yuan 
执行sql如下：
select HIGHLIGHT(title,pre_tags : ['<b>'], post_tags : ['</b>']  ) FROM recom_item_property_20170927 where title like '%aa%'
报错如下：
 Error: {"error":{"root_cause":[{"type":"parser_exception","reason":"syntax error, expect RPAREN, actual VARIANT :"}],"type":"parser_exception","reason":"syntax error, expect RPAREN, actual VARIANT :"},"status":500}
感觉是嵌套函数导致的，对应版本是2.3.4.0

**Comment by JacksonMu** [comment]
@shi-yuan 明白啦，是要放到注释里面，多谢了

**Comment by JacksonMu** [comment]
@shi-yuan 还有个问题就是，我只想将我的匹配词高亮怎么做呢，例如上面sql中只高亮结果中的“aa”，那些option有使用说明么？

**Comment by JacksonMu** [comment]
@shi-yuan 我将explain的json放到head里面执行是可以做到的，但是在sql插件里面执行就将全部的都包起来，这就奇怪了。难道sql执行的时候不是执行的explain之后的sql？

**Comment by shi-yuan** [comment]
options的说明，可以看看es的官方文档
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html#highlighting-settings

**Comment by shi-yuan** [comment]
json放到head里面执行的，应该和sql插件里面执行的，结果一致吧

**Comment by JacksonMu** [comment]
![sql](https://user-images.githubusercontent.com/8372189/38909304-ae44297a-42f6-11e8-9ca1-d6ca49173372.png)
![json](https://user-images.githubusercontent.com/8372189/38909320-bff7abc4-42f6-11e8-9850-e7311d22fc09.png)
@shi-yuan 这两个结果分别是执行SQL和json放到head里面执行的结果，<em>包的范围不一样

**Comment by JacksonMu** [comment]
@shi-yuan 上面红色的是执行SQL的结果，下面黑色的是head执行的结果，我们期望下面这种，通过SQL能实现么？

**Comment by JacksonMu** [comment]
@shi-yuan 咱们的版本不一致，我用的是2.3.4（ES也是这个版本），您的比较新

**Comment by shi-yuan** [comment]
我修改的elastic2.4.6分支，打包测试，没问题呢
![1](https://user-images.githubusercontent.com/8057153/39392218-ccb96a0a-4ae4-11e8-8ea0-d018b164b1a3.png)
