### ISSUE TITLE
elasticsearch-sql 如何处理深分页问题， 本身支持吗？

### ISSUE THREAD

**Issue by 8plat** [NLPchina/elasticsearch-sql#659]
根据条件筛选完毕后 有 40万数据，我需要分页取出，因为存在深分页的问题后面的查询越来越慢。最后一页基本查询不出来。
SELECT * FROM member_info  where  IS_PASS_MESS_VERT = '1'  AND APPLY_TYPE ='10' 
LIMIT 399990,400000

**Comment by shi-yuan** [comment]
插件本身处理的是explain sql，关于深分页的问题，您可以考虑[Scroll](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html)和[Search After](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html)

**Comment by leonlu001** [comment]
Es有限制，只给前10万条数据，你可以增加查询条件，或者时间切片查询。发自我的华为手机-------- 原始邮件 --------主题：[NLPchina/elasticsearch-sql] elasticsearch-sql 如何处理深分页问题， 本身支持吗？ (#659)发件人：8plat 收件人：NLPchina/elasticsearch-sql 抄送：Subscribed 根据条件筛选完毕后 有 40万数据，我需要分页取出，因为存在深分页的问题后面的查询越来越慢。最后一页基本查询不出来。
SELECT * FROM member_info  where  IS_PASS_MESS_VERT = '1'  AND APPLY_TYPE ='10'
LIMIT 399990,400000

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/NLPchina/elasticsearch-sql","title":"NLPchina/elasticsearch-sql","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/NLPchina/elasticsearch-sql"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"elasticsearch-sql 如何处理深分页问题， 本身支持吗？ (#659)"}],"action":{"name":"View Issue","url":"https://github.com/NLPchina/elasticsearch-sql/issues/659"}}}

**Comment by 8plat** [comment]
请问下  USE_SCROLL(100,1000)     其中 1000  表示什么意思

**Comment by 8plat** [comment]
请问下 USE_SCROLL(100,1000) 其中 1000 表示什么意思

**Comment by 8plat** [comment]
请问下   USE_SCROLL(100,10000) 中第二个参数代表的 是 时间吗 ？

**Comment by shi-yuan** [comment]
[Keeping the search context alive](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html#scroll-search-context)
