### ISSUE TITLE
Support scan and scroll search type

### ISSUE THREAD

**Issue by dmfenton** [NLPchina/elasticsearch-sql#69]
When making requests for a lot of rows there is a big performance penalty with either requesting everything at once or using offsets. Scan and scroll lets you efficiently pull many thousands of rows from ES.

See: https://www.elastic.co/guide/en/elasticsearch/guide/current/scan-scroll.html

**Comment by eliranmoyal** [comment]
What do you say about something like an hint?
" USE_SCROLL(docsPerFetch,timeoutInMilli)" with defaults of 10000,10000

For example this query:
SELECT /*! USE_SCROLL(100,5000)*/ gender,firstname,balance FROM  accounts
will return you a searchResponse with valid scrollId to scroll with.

**Comment by dmfenton** [comment]
I would say that you should just default to this search type without exposing it the the end user.

Also, the number of results returned in each scroll is `shards * scroll size`. In testing this, I came up with a scroll size of 40. With 5 shards that gives me 200 rows per request. The performance worked fell for the specific type of data I was storing. See this PR: https://github.com/koopjs/koop-escache/pull/5

**Comment by eliranmoyal** [comment]
It's a bit problem to set it as default because on its main core elasticsearch-sql just translates sql to ActionRequest and execute it.
And from what i found the first query on scroll does not return any docs, and that is not what I think it's the best for simple users.
Yeah you are right, But I believe that the best scroll size is depends on size of docs + network + elasticsearch cpu and ram and num of docs you want to fetch eventually.
I accept that  10k is really big so i'll change it but this is why i let you choose with parameters on the hint :)

It's working right now you can check the latest version 1.4
and read about it on the wiki
https://github.com/NLPchina/elasticsearch-sql/wiki/Scroll

**Comment by dmfenton** [comment]
This works for me :+1: 
Thanks for the great work!
