### ISSUE TITLE
Help with understanding of codebase

### ISSUE THREAD

**Issue by anupamaggarwal** [NLPchina/elasticsearch-sql#78]
Hi, I am trying to understand the inner workings of the project in order to implement something similar for a related project,  Is the SQL->ES written using lex(jlex)/yacc(CUP) or entirely custom written,sorry if its the wrong forum to ask this but I wasn't able to figure out from the codebase.

**Comment by eliranmoyal** [comment]
1. We use alibaba [druid](https://github.com/alibaba/druid) in order to translate the string to SqlExpr.
2.On Normal select - We take the sqlExpr and:
 * translates the "from" to index and type.
 * translates the Where to elastcisearch filter
 * creates the elastcisearch request.

For join , delete and aggregations it's a bit more complicated

if you have any other questions feel free to send me an email. my email can be found on pom.xml
